#!/usr/bin/env python3
import argparse
import csv
import pathlib
import re
import sys


ROOT = pathlib.Path(__file__).resolve().parents[1]
MATRIX_PATH = ROOT / "config" / "feature-matrix.tsv"
MAKEFILE = ROOT / "Makefile"
SKILL = ROOT / "skills" / "waveshare-esp32s3-amoled" / "SKILL.md"
HELPER = ROOT / "skills" / "waveshare-esp32s3-amoled" / "scripts" / "waveshare-arduino-cli.sh"


REQUIRED_COLUMNS = {
    "id",
    "priority",
    "name",
    "build_target",
    "smoke_target",
    "check_script",
    "sketch",
    "doc",
    "skill_action",
    "audio_mode",
    "status",
}

STATUS_VALUES = {"verified", "partial", "required_external", "required_quiet_window"}
AUDIO_VALUES = {"none", "conditional", "audio", "non_audio_control"}


def read_text(path: pathlib.Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return ""


def make_targets(makefile_text: str) -> set[str]:
    targets: set[str] = set()
    for line in makefile_text.splitlines():
        if not line or line.startswith("\t") or line.startswith("."):
            continue
        match = re.match(r"^([A-Za-z0-9_.-]+):(?:\s|$)", line)
        if match:
            targets.add(match.group(1))
    return targets


def load_matrix(path: pathlib.Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        if not reader.fieldnames:
            raise SystemExit(f"{path} is empty")
        missing = REQUIRED_COLUMNS - set(reader.fieldnames)
        if missing:
            raise SystemExit(f"{path} missing columns: {sorted(missing)}")
        return [{key: (value or "").strip() for key, value in row.items()} for row in reader]


def exists_path(value: str) -> bool:
    return (ROOT / value).exists()


def render_markdown(rows: list[dict[str, str]], issues: list[str]) -> str:
    lines = [
        "# Hardware Verification Matrix",
        "",
        "Generated by `scripts/feature-matrix-check.py --markdown`.",
        "",
        "| ID | Priority | Status | Audio mode | Build | Smoke | Doc |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        lines.append(
            "| {id} | {priority} | {status} | {audio_mode} | `{build_target}` | `{smoke_target}` | `{doc}` |".format(
                **row
            )
        )
    lines.extend(["", "## Issues", ""])
    if issues:
        lines.extend(f"- {issue}" for issue in issues)
    else:
        lines.append("- None")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Check feature automation coverage for the Waveshare board.")
    parser.add_argument("--matrix", default=str(MATRIX_PATH))
    parser.add_argument("--markdown", action="store_true", help="Print a markdown report.")
    args = parser.parse_args()

    matrix_path = pathlib.Path(args.matrix)
    rows = load_matrix(matrix_path)
    makefile_text = read_text(MAKEFILE)
    skill_text = read_text(SKILL)
    helper_text = read_text(HELPER)
    targets = make_targets(makefile_text)

    issues: list[str] = []
    seen_ids: set[str] = set()
    for index, row in enumerate(rows, start=2):
        row_id = row["id"]
        if not row_id:
            issues.append(f"row {index}: empty id")
            continue
        if row_id in seen_ids:
            issues.append(f"{row_id}: duplicate id")
        seen_ids.add(row_id)

        if row["status"] not in STATUS_VALUES:
            issues.append(f"{row_id}: unsupported status {row['status']!r}")
        if row["audio_mode"] not in AUDIO_VALUES:
            issues.append(f"{row_id}: unsupported audio_mode {row['audio_mode']!r}")

        for key in ("build_target", "smoke_target"):
            target = row[key]
            if target and target not in targets:
                issues.append(f"{row_id}: Makefile target missing: {target}")

        for key in ("check_script", "sketch", "doc"):
            value = row[key]
            if value and not exists_path(value):
                issues.append(f"{row_id}: path missing for {key}: {value}")

        skill_action = row["skill_action"]
        if skill_action:
            if skill_action not in skill_text:
                issues.append(f"{row_id}: skill action not mentioned in SKILL.md: {skill_action}")
            if skill_action not in helper_text:
                issues.append(f"{row_id}: helper action not mentioned: {skill_action}")

    required_ids = {
        "official-demos",
        "xiaozhi-ai",
        "cloud-ai-terminal",
        "offline-voice",
        "lvgl-visual-agent",
        "imu-interaction",
        "power-lifecycle",
        "desk-widget",
        "iot-panel",
        "esp-claw-agent",
        "tinyml-imu",
        "audio-front-end",
    }
    missing_ids = required_ids - seen_ids
    if missing_ids:
        issues.append(f"missing required feature ids: {sorted(missing_ids)}")

    if args.markdown:
        print(render_markdown(rows, issues), end="")
    else:
        verified = sum(1 for row in rows if row["status"] == "verified")
        partial = sum(1 for row in rows if row["status"] == "partial")
        external = len(rows) - verified - partial
        print(
            "feature_matrix_summary "
            f"features={len(rows)} verified={verified} partial={partial} external_or_quiet={external} "
            f"issues={len(issues)}"
        )
        for issue in issues:
            print(f"feature_matrix_issue {issue}")

    return 1 if issues else 0


if __name__ == "__main__":
    sys.exit(main())
