#!/usr/bin/env python3
import argparse
import csv
import json
import pathlib
import sys
from typing import Any


ROOT = pathlib.Path(__file__).resolve().parents[1]
MATRIX_PATH = ROOT / "config" / "feature-matrix.tsv"
SUITE_ROOT = ROOT / ".logs" / "hardware-smoke-suite"


def load_matrix(path: pathlib.Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        if not reader.fieldnames:
            raise SystemExit(f"{path} is empty")
        return [{key: (value or "").strip() for key, value in row.items()} for row in reader]


def verified_bullets(doc_path: pathlib.Path) -> list[str]:
    if not doc_path.exists():
        return []
    lines = doc_path.read_text(encoding="utf-8").splitlines()
    in_section = False
    bullets: list[str] = []
    for line in lines:
        if line.strip() == "## Verified Locally":
            in_section = True
            continue
        if in_section and line.startswith("## "):
            break
        if in_section and line.startswith("- "):
            bullets.append(line[2:].strip())
    return bullets


def load_suite_results(root: pathlib.Path) -> dict[str, dict[str, Any]]:
    latest: dict[str, dict[str, Any]] = {}
    if not root.exists():
        return latest
    for summary_path in sorted(root.glob("*/summary.json")):
        try:
            payload = json.loads(summary_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        generated_at = str(payload.get("generated_at", ""))
        for item in payload.get("results", []):
            if not isinstance(item, dict) or "id" not in item:
                continue
            row_id = str(item["id"])
            record = dict(item)
            record["summary"] = str(summary_path)
            record["generated_at"] = generated_at
            if row_id not in latest or generated_at >= str(latest[row_id].get("generated_at", "")):
                latest[row_id] = record
    return latest


def posture(row: dict[str, str], bullets: list[str], suite: dict[str, Any] | None) -> str:
    if row["status"] == "required_external":
        return "external-gated"
    if row["status"] == "required_quiet_window":
        return "quiet-window-gated"
    if row["audio_mode"] == "audio":
        return "audio-gated"
    if suite and suite.get("status") == "passed":
        return "suite-passed"
    if not bullets:
        return "missing-doc-evidence"
    if row["status"] == "verified":
        return "documented-verified"
    return "documented-partial"


def next_gap(row: dict[str, str], bullets: list[str], suite: dict[str, Any] | None) -> str:
    if row["status"] == "required_external":
        return "Needs external firmware/source environment evidence."
    if row["status"] == "required_quiet_window":
        return "Needs an explicit quiet-window audio run."
    if row["audio_mode"] == "audio":
        return "Needs supervised audio hardware evidence."
    if not bullets:
        return "Add a Verified Locally section with exact build/smoke commands and outcomes."
    if not suite:
        return "Run through hardware-smoke-suite when this lane is safe to include."
    if suite.get("status") != "passed":
        return "Investigate latest suite failure."
    if row["status"] == "partial":
        return "Decide what remains before promoting matrix status to verified."
    return "No immediate evidence gap."


def rel(path: str | pathlib.Path) -> str:
    try:
        return str(pathlib.Path(path).resolve().relative_to(ROOT))
    except (OSError, ValueError):
        return str(path)


def render_markdown(rows: list[dict[str, str]], suite_results: dict[str, dict[str, Any]]) -> str:
    lines = [
        "# Hardware Evidence Audit",
        "",
        "Generated by `scripts/hardware-evidence-audit.py --markdown`.",
        "",
        "This report audits evidence surfaces only. It does not prove completion by itself.",
        "",
        "| ID | Priority | Matrix status | Audio mode | Doc evidence | Latest suite | Posture | Next gap |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    details: list[str] = []
    for row in rows:
        bullets = verified_bullets(ROOT / row["doc"])
        suite = suite_results.get(row["id"])
        suite_text = "missing"
        if suite:
            suite_text = f"{suite.get('status', 'unknown')} `{rel(str(suite.get('summary', '')))}`"
        row_posture = posture(row, bullets, suite)
        lines.append(
            "| {id} | {priority} | {status} | {audio_mode} | {doc_count} item(s) | {suite_text} | {posture} | {gap} |".format(
                id=row["id"],
                priority=row["priority"],
                status=row["status"],
                audio_mode=row["audio_mode"],
                doc_count=len(bullets),
                suite_text=suite_text,
                posture=row_posture,
                gap=next_gap(row, bullets, suite),
            )
        )
        details.extend(["", f"## {row['id']}", "", f"- Doc: `{row['doc']}`"])
        if suite:
            details.append(f"- Latest suite summary: `{rel(str(suite.get('summary', '')))}`")
            details.append(f"- Latest suite status: `{suite.get('status', 'unknown')}`")
        else:
            details.append("- Latest suite summary: missing")
        if bullets:
            details.append("- Verified Locally:")
            details.extend(f"  - {item}" for item in bullets)
        else:
            details.append("- Verified Locally: missing")
    lines.extend(details)
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Audit feature evidence docs and hardware smoke suite summaries.")
    parser.add_argument("--matrix", default=str(MATRIX_PATH))
    parser.add_argument("--suite-root", default=str(SUITE_ROOT))
    parser.add_argument("--markdown", action="store_true")
    args = parser.parse_args()

    rows = load_matrix(pathlib.Path(args.matrix))
    suite_results = load_suite_results(pathlib.Path(args.suite_root))
    if args.markdown:
        print(render_markdown(rows, suite_results), end="")
    else:
        missing_doc = 0
        missing_suite = 0
        for row in rows:
            bullets = verified_bullets(ROOT / row["doc"])
            suite = suite_results.get(row["id"])
            if not bullets:
                missing_doc += 1
            if not suite:
                missing_suite += 1
            print(
                "evidence_audit "
                f"id={row['id']} status={row['status']} audio={row['audio_mode']} "
                f"doc_items={len(bullets)} suite={suite.get('status', 'missing') if suite else 'missing'} "
                f"posture={posture(row, bullets, suite)}"
            )
        print(
            "evidence_audit_summary "
            f"features={len(rows)} missing_doc={missing_doc} missing_suite={missing_suite}"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
